# Generated by Django 4.1.6 on 2023-07-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Brand Name'),
        ),
    ]
