# Generated by Django 4.1.6 on 2023-07-08 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_slug'),
        ('product', '0008_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_item', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
