# Generated by Django 4.1.6 on 2023-07-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=None, max_length=255, verbose_name='Item Slug'),
            preserve_default=False,
        ),
    ]
