# Generated by Django 4.1.6 on 2023-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reservation Name'),
        ),
    ]
