# Generated by Django 4.1.6 on 2023-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default=None, max_length=255, verbose_name='Supplier Slug'),
            preserve_default=False,
        ),
    ]
